name: Release to pub.dev

on:
  workflow_dispatch:
  push:
    # TODO: Re-enable
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  # test:
  #   name: Test
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  publish:
    # needs: [test]
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
