name: Release to pub.dev

on:
  workflow_dispatch:
  push: #todo:remove
  release:
    types: [ created ]


jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    name: Publish
    permissions:
      id-token: write # This is required for authentication using OIDC
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      
      - uses: dart-lang/setup-dart@v1

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Add pub token
        run: echo ${{secrets.OAUTH_ACCESS_TOKEN}} | dart pub token add https://pub.dev

      - name: Install dependencies
        run: dart pub get

      - name: code format
        run: dart format lib/*/*.dart lib/*.dart

      - name: Publish pkg
        run: dart pub publish --server=https://pub.dartlang.org -f
